spring:
  profiles:
    active: LOCAL

---

spring:
  profiles: LOCAL
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  jmx:
    enabled: false

datasource:
  solarWarServerDb:
    name: solarWarServerDb
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/solar_war_server
    username: root
    password: lanfear

logging:
  file: /home/solarwarserver/app/logs/solar-war-server.log
  level:
    com.hollonconsulting.solarwars.server: 'DEBUG'
    org.springframework: 'WARN'
    org.springframework.security: 'OFF'
    org.hiberante: DEBUG

#server:
#  port: 9000
#  ssl:
#    key-store: keystore.p12
#    key-store-password: lanfear
#    keyStoreType: PKCS12
#    keyAlias: tomcat